# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a03971bfc1b1ee4d6b92e2a5c8d3e161e931a287a712c367a68818055ed97c5a0892e83fa2efacfb9c6b804214989aee1441ab4ebb4d2300aec192d8eb55079

test:
  secret_key_base: 0f4485de6599c0e3d714c887004eb119d8e88250b55f9c5b57bece6623eaba5d6f30d0285b533514079c741b689dbdb62aefb811dbccf21f8228400ce80ee356

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
